### PR TITLE
[WIP] Refactor SocialEditRemoveUserRegistration class

### PR DESCRIPTION
**Pull request by anjarfr**

### CODE REVIEW

**Comment by anjarfr** [comment]
Tried to run this locally, and the same error messages as before appears :(

**Comment by anjarfr** [comment]
What was the purpose of this pull request @hambro?

**Comment by hambro** [comment]
The original purpose was to fix `SocialEditRemoveUserRegistration` in a DRY way. 
The current solution in master is considered a "temporary" fix. 

I did not have time to test the refactoring, so that's why the quick'n'dirty fix was merged I guess.

**Comment by anjarfr** [comment]
Yes, but _how_ did you fix `SocialEditRemoveUserRegistration` with this commit? As it didn't resolve the original bug, I figure this is an overall improvement to the app, and that it is still a work in progress. If not, you can remove the [WIP]-label. So, I'm wondering what is improved specifically, and what more needs to be done?

**Comment by hambro** [comment]
The bug was how the Bedpres view was subclassed from the Event-view. 
The subclassed view accessed variables that did not make sense.
So, in master branch, this was fixed by duplicating the whole CBV and removing incompatible code. 
The duplication included a _lot_ of common code.
This WIP refactored out the common code to avoid this "problem". 

This PR might not fix the issue, but rather a start. As I said, I haven't tested it.
I.e. this branch can be deleted if we are happy with the current fix in master.

**Comment by anjarfr** [comment]
I think the fix in master is a dirty fix, and will be improved. I also think think we should continue this branch :-) so just needed to understand what has been done.

**Comment by hambro** [comment]
I'll try and explain some of the stuff tomorrow :)

**Pull request closed without merging**
